% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Stats Lab 8},
  pdfauthor={Wynona},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Stats Lab 8}
\author{Wynona}
\date{2024-03-14}

\begin{document}
\maketitle

In this case, we are only interested in whether or not we found the
disease in the sampled forest or not.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tree\_disease\_df}\OtherTok{\textless{}{-}}\FunctionTok{read.csv}\NormalTok{(}\StringTok{"\textasciitilde{}/ENV 872/EDA\_Spring2024/Misc./disease.csv"}\NormalTok{, }\AttributeTok{header=}\NormalTok{T)}
\FunctionTok{colnames}\NormalTok{(tree\_disease\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "growth"       "state"        "basal_area"   "agb"          "old"         
## [6] "temp_anomaly" "disease"
\end{verbatim}

\hypertarget{question-1}{%
\subsection{Question 1}\label{question-1}}

Start by fitting an intercept-only model: disease = β0 Call this model
`fit\_1'.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_1}\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(disease}\SpecialCharTok{\textasciitilde{}}\DecValTok{1}\NormalTok{, }\AttributeTok{family=}\StringTok{"binomial"}\NormalTok{, }\AttributeTok{data=}\NormalTok{tree\_disease\_df)}
\FunctionTok{summary}\NormalTok{(fit\_1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = disease ~ 1, family = "binomial", data = tree_disease_df)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)   
## (Intercept)   0.3888     0.1289   3.017  0.00256 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 337.3  on 249  degrees of freedom
## Residual deviance: 337.3  on 249  degrees of freedom
## AIC: 339.3
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\item
  Report the estimated value of β0. What does it correspond to?
  \textgreater Answer: The estimated value of β0 is 0.3888. This
  corresponds to the log odds of finding disease in a sampled forest.
\item
  Given the estimate of the intercept, what is the predicted probability
  (i.e.~ˆp) of finding the disease in a forest? \textgreater Answer: The
  probability of finding the disease in a forest in 0.5959938.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p\_disease}\OtherTok{\textless{}{-}}\FunctionTok{exp}\NormalTok{(}\FloatTok{0.3888}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{+}\FunctionTok{exp}\NormalTok{(}\FloatTok{0.3888}\NormalTok{))}
\NormalTok{p\_disease}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5959938
\end{verbatim}

\hypertarget{question-2}{%
\subsection{Question 2}\label{question-2}}

Now suppose you hypothesize that disease status differs between
old-growth and new-growth forests. Create a binary indicator variable
from the growth variable. Code this variable as 1 if the sample is from
an old-growth forest, and 0 otherwise. (\#Note: This was already done in
the dataset provided.) Next, expand on the model above by including this
new indicator variable, as follows: disease = β0 + old.growthβ1. Call
this model `fit\_2'.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_2}\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(disease}\SpecialCharTok{\textasciitilde{}}\NormalTok{old, }\AttributeTok{family=}\StringTok{"binomial"}\NormalTok{, }\AttributeTok{data=}\NormalTok{tree\_disease\_df)}
\FunctionTok{summary}\NormalTok{(fit\_2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = disease ~ old, family = "binomial", data = tree_disease_df)
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)   0.7053     0.1909   3.695  0.00022 ***
## old          -0.6100     0.2613  -2.335  0.01956 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 337.30  on 249  degrees of freedom
## Residual deviance: 331.78  on 248  degrees of freedom
## AIC: 335.78
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Report the estimate of β0. What does it represent, and how does it
  compare to the estimate from question 1? \textgreater Answer: The
  estimate of β0 is 0.7053 with a standard error of 0.1909, a z-value of
  3.695 and a p-value of 0.00022. It represents the log odds of finding
  the disease in new growth forests. It is almost twice as large as the
  estimate in question 1.
\end{enumerate}

\#NOTES ONLY report the estimate, the standard error. the p value is
lower than 0.05. we conclude there is a difference between this and that

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Based on your estimates from the model, what is the predicted
  probability of finding the disease in an old-growth forest?
  \textgreater Answer: The probability of finding the disease in
  old-growth forests is 0.523807. The log odds of finding the disease in
  old-growth forests is 0.0953.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{log\_odds\_disease\_old}\OtherTok{\textless{}{-}}\FloatTok{0.7053}\SpecialCharTok{+}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{0.6100}\NormalTok{)}
\NormalTok{log\_odds\_disease\_old}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0953
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p\_disease\_oldforests}\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{exp}\NormalTok{(}\FloatTok{0.7053{-}0.6100}\NormalTok{))}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{+}\FunctionTok{exp}\NormalTok{(}\FloatTok{0.7053{-}0.6100}\NormalTok{))}
\NormalTok{p\_disease\_oldforests}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.523807
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Based on your estimates from the model, What is the predicted
  probability of finding the disease in a new-growth forest?
  \textgreater Answer: 0.6693618 is the predicted probability of finding
  the disease in a new-growth forest.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p\_disease\_newforests}\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{exp}\NormalTok{(}\FloatTok{0.7053}\NormalTok{))}\SpecialCharTok{/}\NormalTok{(}\DecValTok{1}\SpecialCharTok{+}\FunctionTok{exp}\NormalTok{(}\FloatTok{0.7053}\NormalTok{))}
\NormalTok{p\_disease\_newforests}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6693618
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Calculate the Odds Ratio for old-growth forest and interpret the
  effect of old- versus new-growth forest on the odds of finding the
  disease. \textgreater Answer: The odds ratio is 0.5433509. The odds of
  finding the disease in old-growth forests is 0.5433509 times the odds
  of finding the disease in new-growth forests.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{0.6100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5433509
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Conduct a hypothesis test in which the null hypothesis is that there
  is no difference in disease status between new-growth and old-growth
  forests \textgreater Answer: The p-value is 0.01892. Since it is less
  than 0.05, we reject the null hypothesis of no difference in disease
  status between new-growth and old-growth forests.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(disease}\SpecialCharTok{\textasciitilde{}}\NormalTok{old, }\AttributeTok{data=}\NormalTok{tree\_disease\_df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  disease by old
## t = 2.3627, df = 247.53, p-value = 0.01892
## alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
## 95 percent confidence interval:
##  0.02421439 0.26687624
## sample estimates:
## mean in group 0 mean in group 1 
##       0.6693548       0.5238095
\end{verbatim}

\hypertarget{question-3}{%
\subsection{Question 3}\label{question-3}}

Now suppose you are interested in building on your model to understand
whether or not basal area (centered on its mean) is associated with
disease status, independent of old-growth status. Now fit a logistic
regression of the following form: disease = β0 + +old.growthβ1 +
basal.areaβ2. Call this model `fit\_3'

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tree\_disease\_df}\OtherTok{\textless{}{-}}\NormalTok{tree\_disease\_df}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{basal\_area\_centered=}\NormalTok{basal\_area}\SpecialCharTok{{-}}\FunctionTok{mean}\NormalTok{(basal\_area))}

\NormalTok{fit\_3}\OtherTok{\textless{}{-}}\FunctionTok{glm}\NormalTok{(disease}\SpecialCharTok{\textasciitilde{}}\NormalTok{old}\SpecialCharTok{+}\NormalTok{basal\_area\_centered, }\AttributeTok{family=}\StringTok{"binomial"}\NormalTok{, }\AttributeTok{data=}\NormalTok{tree\_disease\_df)}
\FunctionTok{summary}\NormalTok{(fit\_3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = disease ~ old + basal_area_centered, family = "binomial", 
##     data = tree_disease_df)
## 
## Coefficients:
##                       Estimate Std. Error z value Pr(>|z|)    
## (Intercept)          7.053e-01  1.916e-01   3.682 0.000232 ***
## old                 -6.101e-01  2.632e-01  -2.318 0.020467 *  
## basal_area_centered  7.968e-05  2.660e-02   0.003 0.997610    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 337.30  on 249  degrees of freedom
## Residual deviance: 331.78  on 247  degrees of freedom
## AIC: 337.78
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Calculate the Odds Ratio for the effect of basal area (centered) on
  disease status and interpret its meaning (not in terms of a hypothesis
  test, but substantively). \textgreater Answer: The odds ratio is 1
  which suggests that the odds of finding a disease versus not finding a
  disease in different basal areas are the same.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{exp}\NormalTok{(}\FloatTok{0.00007968}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.00008
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Conduct a hypothesis test for the effect of basal area (centered) on
  disease status under the null hypothesis of no effect.
  \textgreater Answer: Based on the summary table about, the p-value is
  0.997610, which is higher than 0.05, and the z-value is 0.003 which
  within -2.96 and 2.96, so the null hypothesis stands. The standard
  error is 0.02659893. Therefore, we can conclude that basal area
  (centered) makes no difference on disease status.
\end{enumerate}

\hypertarget{question-4}{%
\subsection{Question 4}\label{question-4}}

Now suppose you wish to better understand whether temperature anomalies
are associated with the disease status of forests. To do this, you fit
the following regression model: disease = β0 + old.growthβ1 +
basal.area.centeredβ2 + temp.anomalyβ3. Call this model `fit\_4'.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_4}\OtherTok{\textless{}{-}}\FunctionTok{glm}\NormalTok{(disease}\SpecialCharTok{\textasciitilde{}}\NormalTok{old}\SpecialCharTok{+}\NormalTok{basal\_area\_centered}\SpecialCharTok{+}\NormalTok{temp\_anomaly, }\AttributeTok{family=}\StringTok{"binomial"}\NormalTok{, }\AttributeTok{data=}\NormalTok{ tree\_disease\_df)}
\FunctionTok{summary}\NormalTok{(fit\_4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = disease ~ old + basal_area_centered + temp_anomaly, 
##     family = "binomial", data = tree_disease_df)
## 
## Coefficients:
##                      Estimate Std. Error z value Pr(>|z|)   
## (Intercept)         -0.030301   0.299682  -0.101  0.91946   
## old                 -0.575481   0.268812  -2.141  0.03229 * 
## basal_area_centered -0.005912   0.027329  -0.216  0.82873   
## temp_anomaly         0.481414   0.154128   3.123  0.00179 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 337.30  on 249  degrees of freedom
## Residual deviance: 321.66  on 246  degrees of freedom
## AIC: 329.66
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\tightlist
\item
  Calculate the Odds Ratio for the effect of temperature anomalies on
  disease status and interpret its meaning as in prior questions.
  \textgreater Answer: The odds ratio for the effect of temperature
  anomalies on disease status is 1.618361 which suggests that the odds
  of finding a disease in trees increases by 1.618361 for a 1 degree C
  increase in temperature anomalies.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{exp}\NormalTok{(}\FloatTok{0.481414}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.618361
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Based on the model you just fit, what factors would you conclude are
  associated with increased odds of disease, and what factors would you
  include are associated with decreased odds of disease? Why? Hint: do
  not simply note which variables were ``statistically significant'',
  since statistical significance is not a measure of scientific
  importance. The factors associated with increased odds of disease is
  if the tree is from new-growth forest and if there are temperature
  anomalies. This suggests that disease thrives in slightly higher
  temperatures and that old-growth forests are more resilient to
  disease. I identified these two variables because the log-odds for
  these variables are not 1 and that the p-values for these variables
  are larger than 0.05 (unlike basal area).
\end{enumerate}

\end{document}
