---
title: "Assignment 1: Introduction"
author: "Wynona Curaming"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Sakai.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took one R class a few years ago, and recently took Dalia's energy modeling class. In the latter, I first encountered github (but linking it with GDrive instead) and did data analysis using Excel and Python. I have conducted data analysis using Excel for various research projects.

2. Are there any components of the course about which you feel confident?

> Answer: None because I didn't use R at all after that class in undergrad. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: Not really. I hope to learn everything successfully. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 
 
> Answer: https://github.com/wynona0405/EDA_Spring2024/tree/main

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
